Haxorelite
Kojizzle/InfinityIncursion pull request #6
Opened 2021-04-27 14:50 UTC by salt431

the horror aspect of CTRASH with an intent on using the persons name to better form the horror atmosphere.

2021-04-27 14:57 UTC, Dylanaitor76 requested changes
Configure Git to ignore the file changes.

2021-04-27 14:57 UTC, Dylanaitor76 commented on horror.py
> +def look():
Needs Context

2021-04-27 15:20 UTC, Dylanaitor76 submitted a review, later dismissed
Try and get rid of the file changes again, they came back when you re did your context.

2021-04-30 14:54 UTC, Lumantere approved these changes

2021-04-30 14:57 UTC, merged